*Scratch file for Numpy concepts*
Keywords 
> np.array > arange > zeros > shape, reshape > eye > random (rand, randn , randint)> .max , .min , .argmax(), .argmin() > dtype > linspace 

In [77]:
%config IPCompleter.greedy=True  # to enable intellisense 

# Section 5 - L18

import numpy as np 
# array 
list_array = [1,2,[3,4],5]
array_array  = np.array(list_array)
print('Numpy array type', array_array)    # ([])

# arange 
array_arange = np.arange(0,10)
print('arange keyword', array_arange)

# zeros 
array_zeros = np.zeros(5)
array_zeros.dtype = int 
print('Zeros keyword - dtype', array_zeros)

# reshape 
array_reshape = np.arange(0,100,5)  # [0-95 in count of 5 - 20 elements]
print('Reshaped', array_reshape.reshape(2,5,2)) # [split into 2 arrays each having 5x2 elements]

# shape
print('Shaped', array_reshape.shape)   # (20,0) - 1D array with 20 elements 

# eye 
array_eye = np.eye(5, dtype= int)  # 5 x 5 identity matrix with int dtype 
print('Identity matrix', array_eye)

# random 
array_random = np.random.rand(2,3)  # prints random number  2 arraylets x 3 
print('Random numbers', array_random)
array_random_int = np.random.randint(1,10,2) # from 1-10 2 random nos 
print('Random int numbers', array_random_int)   # prints 6,4 
array_random_normal = np.random.randn(3,2)  
print('Random normal numbers', array_random_normal)  # prints 3 arraylets x 2 random normal number types 

# linspace 
array_linspace = np.linspace(10,20,5) # linearly divide the space into 4 
print('Linspace', array_linspace)
print('Linspace endpoint excluded',np.linspace(20,30,4,endpoint=False)) 
# dont include the end point and divide space into 4 


# max , min , argmax, argmin 
# Linspace [10.  12.5 15.  17.5 20. ]
print(max(array_linspace))   #20.0
print(array_linspace.min())   # 10.0
print(array_linspace.argmax()) # 4
print(array_linspace.argmin()) # 0


Numpy array type [1 2 list([3, 4]) 5]
arange keyword [0 1 2 3 4 5 6 7 8 9]
Zeros keyword - dtype [0 0 0 0 0 0 0 0 0 0]
Reshaped [[[ 0  5]
  [10 15]
  [20 25]
  [30 35]
  [40 45]]

 [[50 55]
  [60 65]
  [70 75]
  [80 85]
  [90 95]]]
Shaped (20,)
Identity matrix [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
Random numbers [[0.78540926 0.47111027 0.81828331]
 [0.25610201 0.50032958 0.42203413]]
Random int numbers [2 8]
Random normal numbers [[ 0.50487672  0.02400474]
 [-0.3941736  -1.57169262]
 [-0.27178736 -0.0917388 ]]
Linspace [10.  12.5 15.  17.5 20. ]
Linspace endpoint excluded [20.  22.5 25.  27.5]
20.0
10.0
4
0


Keywords
> Section 5 - L20
> slicing a numpy array > broadcast sliced arrays > .copy() , reference to array concept > 2D array indexing > slicing a 2D array > array elements bool and condition check >

In [ ]:
%config IPCompleter.greedy=True  # to enable intellisense 
# Section 5 - L20
# count always starts with 0 and ends with n-1 
slice_array = np.arange(1,21) # 1-20
print(slice_array)      # 1-20 
print(slice_array[0:20])   # 1-20 - actual elements are 19 - array ends with n-1 so adding +1 to display 
print(slice_array[:11]) # 1-11
print(slice_array[0:6]) # 1-6
print(slice_array[11:19:2]) # 

# Do some broadcast reference 

broadcast_array = slice_array[0:5] # 1-5  
broadcast_array[0:5] = [5,5,5,5,5]
print(broadcast_array) # [5 5 5 5 5]
print(slice_array) # [ 5  5  5  5  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
# making the array also to be broadcasted - dangerous manipulation

# revert the broadcast 
broadcast_array[0:5] = [1,2,3,4,5]
print(slice_array)

# Do some broadcast copy 
broadcast_copy = slice_array.copy()    # counts upto n-1 
print('Copy of slice_array', broadcast_copy) 
broadcast_copy[0:5] = [5,5,5,5,5]
print('After broadcast', broadcast_copy) # [5  5  5  5  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
print('slice_arry After copy broadcast', slice_array)  
# no change unless like the above broadcast reference 

# indexing in 2D array structures 
array_indexing= np.array([[1,2,3],[4,5,6],[7,8,9]])  
# use the bracketing thingy to remember the braces ([]) 1D , ([[],[]]) 2D
print(array_indexing)

# double bracket notation 
# remember indexing starts from 0 
print('Double notation indexing', array_indexing[1][1])  #[row][col]

# single bracket notation 
print('Single notation indexing', array_indexing[1,1]) # [row, col]

# index elements 
print('Subsections of 2D array', array_indexing[:1,:]) # print 0th row and all columns [[1,2,3]]
print('Subsected of 2D array', array_indexing[:2,:2])  # prints [[1,2],[4,5]]

# boolean array check - 
# checks for the elements for a condition and returns a boolean of array with True and false

bool_array = np.arange(1,11)
print(bool_array) # [1-10]
bol_array = bool_array>4   # returns True, false 
print('booled array 1', bool_array[bol_array])      # indexing the bool array to original array returns the True value 

# (OR)
      
print('booled array 2', bool_array[bool_array>4])

# complex arrays 
array_complex = np.arange(50).reshape(2,5,5)
print('Complex array\n', array_complex)
print('Subsectioning 1st arraylet', array_complex[0,:2,:3]) # [arraylet, row, col]
# prints 1st arraylet , upto 1st row and 2nd column [0,1,2][5,6,7]

print('Subsectioning 2nd arraylet', array_complex[1,3:,:4]) 
# prints 2nd arraylet, from 3rd row to 3rd column - [40,41,42,43][45,46,47,48]

print('Subsectioning using double bracket',array_complex[0][1:,:3]) # [arraylet][row, column]
# prints 1st arraylet, from 1st row to end and to 2nd column  - [5 6 7][10 11 12][15 16 17][20 21 22]





Keywords 
> Section 5 - L21 
> Array with array > array with scalar > Universal array functions 
> array basic ops > array max, min > np.sqrt, .sin, .max, .min 
> checkout the documentation of the array operations 
https://docs.scipy.org/doc/numpy/reference/ufuncs.html