In [ ]:
print('Hello data')

In [2]:
# Series
from pandas import *

series_odd = Series([1,3,5,7,9], index=[1,2,3,4,5])
series_odd
dictionary_sal = {'Vig':3500, 'Tha':3000,'Ara':2500}
dictionary_sal
series_sal = Series(dictionary_sal)
series_sal


Vig    3500
Tha    3000
Ara    2500
dtype: int64

In [6]:
# Dataframes 
from pandas import DataFrame

data_set = {'Name':['Vig','Tha','Ara','Ani','Sud'],
            'Age':[29,27,26,27,29],
            'Salary':[3500,3250,3000,2750,2500],
            'Company':['Catalysts', 'Anker','Aachenuni','Siemens','Valeo']
           }
dataframe_profile = DataFrame(data_set, index=[1,2,3,4,5])

In [7]:
# Changing column sequence 
dataframe_profile = DataFrame(dataframe_profile, columns=['Name', 'Salary', 'Company', 'Age'])
dataframe_profile

Name  Salary    Company  Age
1  Vig    3500  Catalysts   29
2  Tha    3250      Anker   27
3  Ara    3000  Aachenuni   26
4  Ani    2750    Siemens   27
5  Sud    2500      Valeo   29

In [8]:
# Transpose of the dataframe
dataframe_profile_t = dataframe_profile.T
dataframe_profile_t

1      2          3        4      5
Name           Vig    Tha        Ara      Ani    Sud
Salary        3500   3250       3000     2750   2500
Company  Catalysts  Anker  Aachenuni  Siemens  Valeo
Age             29     27         26       27     29

In [9]:
# reindex keyword - Series 
series_even = Series([2,4,6,8,10], index=[5,4,3,2,1])
series_even = series_even.reindex([1,2,3,4,5])
series_even

1    10
2     8
3     6
4     4
5     2
dtype: int64

In [10]:
# reindex keyword - Dataframe 
dataframe_reindex = DataFrame(data_set, index=[5,4,3,2,1])
dataframe_reindex
dataframe_reindex = dataframe_reindex.reindex(index=[3,2,1,5,4])
dataframe_reindex

Name  Age  Salary    Company
3  Ara   26    3000  Aachenuni
2  Ani   27    2750    Siemens
1  Sud   29    2500      Valeo
5  Vig   29    3500  Catalysts
4  Tha   27    3250      Anker

In [11]:
# changing colum sequence 
columnsequence = ['Salary', 'Age','Company','Name']
dataframe_reindex = DataFrame(dataframe_reindex, columns=columnsequence)
dataframe_reindex

Salary  Age    Company Name
3    3000   26  Aachenuni  Ara
2    2750   27    Siemens  Ani
1    2500   29      Valeo  Sud
5    3500   29  Catalysts  Vig
4    3250   27      Anker  Tha

In [12]:
# Delete rows and columns 
# Drop 

# rows 
dataframe_drop = DataFrame(data_set, index=[1,2,3,4,5])
dataframe_drop.drop(5)  # delete row 
dataframe_drop.drop('Company', axis=1)


Name  Age  Salary
1  Vig   29    3500
2  Tha   27    3250
3  Ara   26    3000
4  Ani   27    2750
5  Sud   29    2500

In [13]:
# Arithmetic ops on series 
from pandas import Series
series_even = Series(series_even, index=[5,4,3,2,1])
series_even 
series_net =  series_even + series_odd
series_net



1    11
2    11
3    11
4    11
5    11
dtype: int64

In [20]:
# Arithmetic ops on Dataframe 
from pandas import DataFrame
weather_set1 = {'Speed':[50,100,150], 
                'Temp':[30,40,50], 
                'Humidity':[60,70,80]
                }
weather_set2 = {'Speed':[50,100,150,200], 
                'Temp':[30,40,50,60], 
                'Humidity':[60,70,80,90]
               }
weatherframe1 = DataFrame(weather_set1, index=[1,2,3])
weatherframe1
weatherframe2 = DataFrame(weather_set2, index=[1,2,3,4])
weatherframe2

weatherframe_net = weatherframe1 + weatherframe2
weatherframe_net = DataFrame(weatherframe_net, columns =['Humidity', 'Speed', 'Temp'])
weatherframe_net


Humidity  Speed   Temp
1     120.0  100.0   60.0
2     140.0  200.0   80.0
3     160.0  300.0  100.0
4       NaN    NaN    NaN

In [22]:
# Operations between Dataframes and Series 

series_op = Series([10,20,30], index = ['Speed', 'Temp', 'Humidity'])
series_op + weatherframe_net

Humidity  Speed   Temp
1     150.0  110.0   80.0
2     170.0  210.0  100.0
3     190.0  310.0  120.0
4       NaN    NaN    NaN

In [33]:
# Sorting dataframe  - sort_index 
dataframe_profile_sort = DataFrame(dataframe_profile, index=[3,1,2,4,5])
dataframe_profile_sort
dataframe_profile_sort.sort_index() # ascending sort by index 
dataframe_profile_sort.sort_index(ascending=False) #descending sort by index 

# Column label sort 
dataframe_profile_sort.sort_index(axis=1) # sorts the column labels 

Age    Company Name  Salary
3   26  Aachenuni  Ara    3000
1   29  Catalysts  Vig    3500
2   27      Anker  Tha    3250
4   27    Siemens  Ani    2750
5   29      Valeo  Sud    2500

In [31]:
# Sorting series - sort 
series_sort = Series([100,200,300,400,500], index=[2,3,4,5,1])
series_sort.sort_index()  # ascending order 
series_sort.sort_index(ascending=False) # descending order 

5    400
4    300
3    200
2    100
1    500
dtype: int64

In [37]:
# Sorting series - sort_values 
series_sort.sort_values(ascending = False)

1    500
5    400
4    300
3    200
2    100
dtype: int64

In [41]:
# Sorting data frames - sort_values 
dataframe_profile_sort.sort_index().sort_values('Salary', ascending = False)

Name  Salary    Company  Age
1  Vig    3500  Catalysts   29
2  Tha    3250      Anker   27
3  Ara    3000  Aachenuni   26
4  Ani    2750    Siemens   27
5  Sud    2500      Valeo   29

In [44]:
# Duplicate index's - index.is_unique 
series_dup = Series([100,200,300,400], index=[1,2,2,3])
series_dup.index.is_unique
dataframe_dup = DataFrame(dataframe_profile, index=[1,2,2,3,4])
dataframe_dup.index.is_unique

False

In [68]:
# Sum - Series , DataFrame 
series_sum = Series([10,20,30,40,50])
sum(series_sum)  #150

dataframe_profile_sum1 = dataframe_profile.drop('Name',1)
# dataframe_profile_sum1
dataframe_profile_sum2 = dataframe_profile_sum1.drop('Company',1)
dataframe_profile_sum2.sum()

Salary    15000
Age         138
dtype: int64

In [73]:
# max , min - idxmax , idxmin 
dataframe_profile_sum2
# dataframe_profile_sum2.idxmax()
# dataframe_profile_sum2.idxmin()

Salary  Age
1    3500   29
2    3250   27
3    3000   26
4    2750   27
5    2500   29

In [6]:
# L126 - Creating numpy array , reshape 

import numpy as np 

array = np.array([1,2,3,4,5,6])
print(array)

# reshape keyword 
print(array.reshape(3,2))  # splits the single array into 3 each with 2 elements 


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
# L127 - keywords - arange, zeros 
a = np.arange(24)
print(a) #[0-24]

# reshape 
a.reshape(2,12)  # 2 arrays with 12 elements each 
a.reshape(2,3,4) # 2 arrays with 3 rows and 4 columns 

zeros = np.zeros(5) # prints it in float data type 
zeros = np.zeros(5, dtype = np.int)
zeros

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


array([0, 0, 0, 0, 0])

In [22]:
# Logspace & Linspace 
import numpy as np 
x = np.linspace(10,20,5)  # splits the space into 5 elements including the end number 
x = np.linspace(10,20,5, endpoint=False, dtype = np.int) # splits the space into 5 elements excluding the end number 
x

y = np.logspace(1.0,2.0,10)
y


array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [63]:
# L129 - slicing & indexing in numpy 
import numpy as np
a = np.arange(24)

b = a[2:7:2]
b    # [2,4,6]

# c = a[2::2]
# c

# d = a[:10:1]
# d


array([2, 4, 6])

In [72]:
# Multidimensional array 
md = np.arange(24)
md_reshaped = md.reshape(3,4,2)
print('Full reshaped\n', md_reshaped,'\n')

# Lets slice this 
print('Sliced\n', md_reshaped[1:])  # slices 0th array and starts from the 1st array set

Full reshaped
 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]] 

Sliced
 [[[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [80]:
md_reshaped = md_reshaped.reshape(2,3,4)
print(md_reshaped)
md_index = md_reshaped[[0,1,1],[1,2,1]]  #first [] represents the array 2nd bracket represents the element list 
md_index

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [16, 17, 18, 19]])

In [86]:
# indexing again 
b = np.array([[1,2,3],[2,3,4],[3,4,5]])
print(b)

c = b[[0,1,2],[1,2,1]]  # needs to print 2,4,4
c

[[1 2 3]
 [2 3 4]
 [3 4 5]]


array([2, 4, 4])

In [91]:
md_reshape_new = md_reshaped.reshape(3,2,4)  # 3 arrays with 2 rows and 4 columns 
print(md_reshape_new)

md_reshape_new[[0,1,2],[1,0,0],[0,1,0]]  # expected to print 4,8,16

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


array([ 4,  9, 16])

In [97]:
od = np.array([[1,2,3],[4,5,6],[7,8,9]])  # one Array with multiple elements 
print(od)

y_1 = od[[0,0],[0,2]]
y_2 = od[[2,0],[2,2]]
y_od = np.array([y_1,y_2])
print(y_od)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3]
 [9 3]]


In [5]:
# Reading email id list from the excel and stripping of the @domain.com
import pandas as pd
import re

xl= pd.ExcelFile("email.xlsx")
df = xl.parse(xl.sheet_names[0])
alpha_list = df.values.tolist()
flattened  = [val for sublist in alpha_list for val in sublist]
newlist = []
pattern1 = r'@[a-zA-Z]*-?[a-zA-Z]*?.de'
pattern2 = r'@[a-zA-Z]*-?[a-zA-Z]*?.com'
pattern3 = r'@[a-zA-Z]*-?[a-zA-Z]*?.at'
pattern4 = r'@[a-zA-Z]*-?[a-zA-Z]*?.ch'

for i in range(len(flattened)):
    if re.search(pattern1, flattened[i]):
        newlist.append(re.sub(pattern1, '', flattened[i]))
    elif re.search(pattern2, flattened[i]):
        newlist.append(re.sub(pattern2, '', flattened[i]))
    elif re.search(pattern3, flattened[i]):
        newlist.append(re.sub(pattern3, '', flattened[i]))
    elif re.search(pattern4, flattened[i]):
        newlist.append(re.sub(pattern4, '', flattened[i]))
        
print(newlist)
print(len(newlist))


['klaus.schumacher', 'winfried.stuerzbecher ', 'markus.griese', 'oliver.priggemeyer', 'catharina.becker', 'diana.hofmann', 'margret.schulenburg', 'florian.howe', 'christian.classen', 'aertle', 'fbohmer', 'mmudra', 'dvonaufschnaiter', 'AHesse ', 'JTreppner', 'Dan.Sauera.com', 'FK', 'OB', 'SeS', 'AlM', 'SF', 'MW', 'RoP', 'TaM', 'SG', 'FM', 'MS', 'm.koerner', 'huber', 'schlegel', 'privatbank', 'abcib.frankfurt', 'jens-christian.meier', 'alexis.plan', 'm.korkmaz', 'f.kramer', 'e.soybay', 'frankfurt', 'thomas.ignatzi', 'carsten.lehr', 'alexandra.lombard', 'marcus.kruber', 'shirin.marquart', 'jan.engel', 'nibcbankdeutschlandag', 'info.frankfurt.', 'information', 'sabine.haertl', 'mario.kuenzel', 'matthias.schneider', 'simone.ausfelder', 'ina.kolanowski', 'sophie.horrion', 'schlichtung', 'susanne.hellmann', 'michael.schrinner', 'ajelunke', 'christoph.vigelius', 'vpebank.berlin2', 'peter.classen', 'hi', 'gunnar.knierim', 'busack', 'thomas.schmitt', 'mvomhagen', 'bernd.marzin', 'b.steege', 'fra